sudo: required
services:
    - docker

before_install:
    - docker build -t abijeethdarwin/docker-fib -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true abijeethdarwin/docker-fib npm run test
    
after_success:
    - docker build -t abijeethdarwin/docker-fib-client ./client
    - docker build -t abijeethdarwin/docker-fib-nginx ./nginx
    - docker build -t abijeethdarwin/docker-fib-server ./server
    - docker build -t abijeethdarwin/docker-fib-workder ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the docker images
    - docker push abijeethdarwin/docker-fib-client
    - docker push abijeethdarwin/docker-fib-nginx
    - docker push abijeethdarwin/docker-fib-server
    - docker push abijeethdarwin/docker-fib-worker
    
